PizzaProjectBackEnd/config/routes.rb
Rails.application.routes.draw do
  post 'order/create', to: 'order#create'
  get 'order/show', to: 'order#view'
  resources :pizzas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

PizzaProjectBackEnd/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

PizzaProjectBackEnd/app/models/order.rb
class Order < ApplicationRecord
  validates :name, :adress, presence: true
  has_many :pizzas, through: :orderlines
end

PizzaProjectBackEnd/app/models/orderline.rb
class Orderline < ApplicationRecord
  belongs_to :order
  belongs_to :pizza
end

PizzaProjectBackEnd/app/models/pizza.rb
class Pizza < ApplicationRecord
  has_many :orders, through: :orderlines
end

PizzaProjectBackEnd/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

PizzaProjectBackEnd/app/controllers/order_controller.rb
class OrderController < ApplicationController    
      skip_before_action :verify_authenticity_token, :only => [:create]
  
def create 
    @name = params[:name]
    @adress = params[:adress]
    @pizzas = params[:pizzas]
    newOrder = Order.new(:name => @name, :adress => @adress)
    newOrder.save
    @pizzas.each do |pizza|
      @orderPizza =Pizza.where(name: pizza).first
      newOrderline = Orderline.new
      newOrderline.order=newOrder
      newOrderline.pizza=@orderPizza
      newOrderline.save
    end
   
     render json: {"message :" => "Order created Succesfully"}
end
  
def view
    @orders= []
    @allOrders = Order.all
    @allOrders.each do |order|
      pizzas = []
      @orderlines=Orderline.where(order: order)
      @orderlines.each do |orderline|
          pizza = Pizza.find(orderline[:pizza_id])
          pizzas.push(pizza)
      end
      @orders.push({order: order ,pizzas: pizzas})
    end
   
end
  
  
end

PizzaProjectBackEnd/app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :set_pizza, only: [:show, :edit, :update, :destroy]

  # GET /pizzas
  # GET /pizzas.json
  def index
    @pizzas = Pizza.all
  end

  # GET /pizzas/1
  # GET /pizzas/1.json
  def show
  end

  # GET /pizzas/new
  def new
    @pizza = Pizza.new
  end

  # GET /pizzas/1/edit
  def edit
  end

  # POST /pizzas
  # POST /pizzas.json
  def create
    @pizza = Pizza.new(pizza_params)

    respond_to do |format|
      if @pizza.save
        format.html { redirect_to @pizza, notice: 'Pizza was successfully created.' }
        format.json { render :show, status: :created, location: @pizza }
      else
        format.html { render :new }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pizzas/1
  # PATCH/PUT /pizzas/1.json
  def update
    respond_to do |format|
      if @pizza.update(pizza_params)
        format.html { redirect_to @pizza, notice: 'Pizza was successfully updated.' }
        format.json { render :show, status: :ok, location: @pizza }
      else
        format.html { render :edit }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzas/1
  # DELETE /pizzas/1.json
  def destroy
    @pizza.destroy
    respond_to do |format|
      format.html { redirect_to pizzas_url, notice: 'Pizza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pizza
      @pizza = Pizza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pizza_params
      params.require(:pizza).permit(:name, :price, :url)
    end
end

PizzaProjectBackEnd/app/helpers/application_helper.rb
module ApplicationHelper
end

PizzaProjectBackEnd/app/helpers/order_c_helper.rb
module OrderCHelper
end

PizzaProjectBackEnd/app/helpers/order_helper.rb
module OrderHelper
end

PizzaProjectBackEnd/app/helpers/pizzas_helper.rb
module PizzasHelper
end

PizzaProjectBackEnd/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

PizzaProjectBackEnd/app/views/order/view.html.erb
<p>Commandes</p>

<table align=center border=1 >
  <tr align-text=center > 
	<th>Name
	<th>Adress
	<th> Pizza
  </tr>
  
  <% @orders.each do |order| %>
  <tr>
    <td> <%= order[:order][:name]  %></td>
    <td> <%= order[:order][:adress] %></td>
    <td>
        <ul >
		        <% order[:pizzas].each do |pizza| %>
              <li><%= pizza[:name] %></li>
            <% end %>
        </ul>
    </td>
  </tr>
  <% end %>
</table>
<br>

PizzaProjectBackEnd/app/views/pizzas/_form.html.erb
<%= form_with(model: pizza, local: true) do |form| %>
  <% if pizza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pizza.errors.count, "error") %> prohibited this pizza from being saved:</h2>

      <ul>
      <% pizza.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

PizzaProjectBackEnd/app/views/pizzas/edit.html.erb
<h1>Editing Pizza</h1>

<%= render 'form', pizza: @pizza %>

<%= link_to 'Show', @pizza %> |
<%= link_to 'Back', pizzas_path %>

PizzaProjectBackEnd/app/views/pizzas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pizzas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pizzas.each do |pizza| %>
      <tr>
        <td><%= pizza.name %></td>
        <td><%= pizza.price %></td>
        <td><img  width="80px" height="80px"  src="<%= pizza.url %>"></td>
        <td><%= link_to 'Show', pizza %></td>
        <td><%= link_to 'Edit', edit_pizza_path(pizza) %></td>
        <td><%= link_to 'Destroy', pizza, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pizza', new_pizza_path %>

PizzaProjectBackEnd/app/views/pizzas/new.html.erb
<h1>New Pizza</h1>

<%= render 'form', pizza: @pizza %>

<%= link_to 'Back', pizzas_path %>

PizzaProjectBackEnd/app/views/pizzas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pizza.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @pizza.price %>
</p>

<p>
  <strong>Url:</strong> 
  <img  width="80px" height="80px"  src="<%= @pizza.url %>">
</p>

<%= link_to 'Edit', edit_pizza_path(@pizza) %> |
<%= link_to 'Back', pizzas_path %>